name: 'Deploy to AWS S3'
description: 'Deploy a static website to AWS S3.'
author: 'Nelson YIMOU'
inputs:
  bucket-name:
    description: 'The name of the S3 bucket to deploy to.'
    required: true
  bucket-region:
    description: 'The AWS region where the S3 bucket is located.'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'The local folder containing the files to deploy.'
    required: true
outputs:
  website-url:
    description: 'The URL of the deployed website.'
runs:
  using: node20
  main: 'main.js'