name: Deployment
on:
  push:
    branches:
      - main
      - dev

env:
  MONGODB_DB_NAME: nelsonyimou_db
jobs:
  test:
    environment: testing
    env:
      MONGODB_CLUSTER_ADDRESS: cluster0.cxppnk9.mongodb.net
      MONGODB_USERNAME: nelsonyimou_db_user
      MONGODB_PASSWORD: fW1R6SEPtnV9S7VG
      PORT: 3000
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: |
          set -o pipefail
          npm start & npx wait-on http://127.0.0.1:$PORT 2>&1 | tee server.log
      - name: Run tests
        run: |
          set -o pipefail
          npm test 2>&1 | tee test.log
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: job-logs
          path: |
            server.log
            test.log
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |        
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
          echo "MONGODB_DB_NAME: ${{ env.MONGODB_DB_NAME }}"
